// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrzqjtafkogyythiamui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyenFqdGFma29neXl0aGlhbXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDQ2NjUsImV4cCI6MjA2NzU4MDY2NX0.aYWamkQNSj7OaIzmcaIX4xuSy-329mKhOVoDGpdo5ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});